### ISSUE TITLE
in Challenges, there's no indication if challenges were filtered to the logged in user's

### ISSUE THREAD

**Issue by julesmeister** [julesmeister/testmanship#5]
There used to be some kind of indicator that shows when the challenges were filtered to only the ones he made. Now, it's not visible, although some kind of button is there to activate this filter.

**Comment by mnmnk43434** [comment]
Hello, we tried to solve the issue.

This is what we did:

Modified the ChallengeStats component to include a visible indicator when user's challenges are filtered. Added a button to toggle the filter and show the current state.

You can review changes in this commit: https://github.com/mnmnk43434/julesmeister-testmanship-5/commit/2bf17368ddeb8b882c431ae6dee68d40955c0e8e.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
